AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to create an S3 bucket.
Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref StaticWebsiteBucket